version: "3.7"

services:
  nodejs:
    build:
      context: ./nodejs/
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: web-root-new4
        target: /var/www/html
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
      - type: bind
        source: ./dhparam/dhparam-2048.pem
        target: /etc/ssl/certs/dhparam-2048.pem
    depends_on:
      - nodejs
    networks:
      - app-network
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - type: volume
        source: certbot-etc
        target: /etc/letsencrypt
      - type: volume
        source: certbot-var
        target: /var/lib/letsencrypt
      - type: volume
        source: web-root-new4
        target: /var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ashishjullia19@gmail.com --agree-tos --no-eff-email --staging -d geekylanetest.com  -d www.geekylanetest.com

volumes:
  certbot-etc:
  certbot-var:
  web-root-new4:

networks:
  app-network:
    driver: bridge